### ISSUE TITLE
stuff isnt loading

### ISSUE THREAD

**Issue by fnfporterhi** [Mr-funkinguy/TKO-B-M-G-A-O#1]
when i tried loading this, it gave me a lot of errors, so i think you left some stuff out
![Screenshot 2022-08-17 2 30 51 PM](https://user-images.githubusercontent.com/99343223/185216094-323f35ff-813d-47e8-b802-3587722fef1e.png)

**Comment by Mr-funkinguy** [comment]
sorry that im late to respond i never got a notification, anyway what song did you try to load?

**Comment by fnfporterhi** [comment]
tko

**Comment by fnfporterhi** [comment]
mind if i fork this and try and fix it?

**Comment by fnfporterhi** [comment]
ok so its showing that you forgot the week 7 part of the assets folder.

**Comment by Mr-funkinguy** [comment]
there is no week 7

**Comment by Mr-funkinguy** [comment]
go to story mode and play it from there

**Comment by fnfporterhi** [comment]
oh thats why lmfao

**Comment by fnfporterhi** [comment]
29 misses, test run on upscroll, (downscroll main but can read upscroll), but after the thing it showed a haxe logo and then took me back to the main menu

**Comment by Mr-funkinguy** [comment]
29 nice
